### ISSUE TITLE
Issue #8-1: Test Case 1 (Date Errors)

### ISSUE THREAD

**Issue by darleneagbayani** [spring2020calendar/eventplanner#22]
Feature:	Check Leap Year Date Errors

	Description:	We need to make sure that the date entered by the user doesn't violate Leap Year Rules.

	Scenario:	Entering Feb/29 in a Leap Year

		Given:	I'm entering the start date and/or the end date.
		When:	I enter Feb/29 and a year.
		  And:	The year can be evenly divided by 4 but not 100. 
		  Or:	The year can be evenly divided by 400.
		Then:	The event planner should accept the date.
		  And:	I will not see warnings unless I violate other rules.

	Scenario:	Entering Feb/29 in a Common Year

		Given:	I'm entering the start date and/or the end date.
		When:	I enter Feb/29 and a year.
  		  And:	The year cannot be evenly divided by 4.
  		  Or:	The year can be evenly divided by 100 but not 400.
		Then:	The event planner will not accept the date.	
		  And:	I will see warnings indicating this date error. The ICS file cannot be generated.

**Comment by yuhanj** [comment]
Feature:	Check Leap Year Date Errors

	Scenario:	Entering Feb/29 in a Leap Year - pass

	Scenario:	Entering Feb/29 in a Common Year - pass
